#!/usr/bin/env ruby

require "optparse"
require "psych"
require "add_vault_tokens"

# Set up command-line option defaults.
options = { prefix: '', renew: true }
options[:prefix] = "#{ENV.fetch('VAULT_ENV')}-" if ENV.has_key?('VAULT_ENV')

# Parse our command-line.
OptionParser.new do |opts|
  opts.banner = "Usage: example.rb [options]"

  opts.on("-p", "--prefix", "Prefix to add to each app name") do |p|
    options[:prefix] = p
  end

  opts.on(nil, "--no-renew", "Do not renew our master token") do |nr|
    options[:renew] = false
  end
end.parse!
paths = ARGV

# Connect to our vault server.
AddVaultTokens.connect

# Renew our master token.
if options[:renew]
  STDERR.puts("Renewing VAULT_MASTER_TOKEN")
  AddVaultTokens.renew_master_token
end

# For each input file, add the appropriate tokens to each app.
paths.each do |path|
  yml = Psych.load_file(path)
  result = AddVaultTokens.add_tokens_to_apps(yml, prefix: options.fetch(:prefix))
  File.write("#{path}.tmp", Psych.dump(result))
  # Atomically overwrite existing file.
  File.rename("#{path}.tmp", path)
end
